// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_zym3aCbQ3",
    "aws_user_pools_web_client_id": "2n15lhk845sucm0k4fejjqcbev"
};


export default awsmobile;
